### ISSUE TITLE
Pie Charts

### ISSUE THREAD

**Issue by RhomGit** [jsuarezruiz/TemplateUI#1]
Hi Javier,

just a quick question regarding https://github.com/jsuarezruiz/TemplateUI#datavisualization
I saw the Xamarin blog post about shapes and am quickly taking a look. Could you recommend an approach for rendering a pie chart please?

**Comment by jsuarezruiz** [comment]
Yes, can use Shapes or SkiaSharp to render it. I intend to include a PieChart in this library.
