### ISSUE TITLE
Where's the code? :-(

### ISSUE THREAD

**Issue by hot33331** [jsuarezruiz/TemplateUI#2]
Hi, maybe I misunderstood the purpose of this repo, but I cannot seem to find source code :-(

**Comment by jsuarezruiz** [comment]
I want to share the code with a good example and with a good documentation. Will commit the code after complete the sample and all the Wiki (in a few days).

**Comment by hot33331** [comment]
Thank you - didn't mean to rush you, was just wondering if I did something wrong here and therefore could not see the code. Everything on the images looks great, thanks for doing this, can't wait to look at the code :-)

**Comment by giuseppenovielli** [comment]
@jsuarezruiz Thanks, very very beautiful work!!

**Comment by angelru** [comment]
woww! I am looking forward to using it
