### ISSUE TITLE
Tag control does not implement propertyChanging for bindable properties

### ISSUE THREAD

**Issue by mkanyo** [jsuarezruiz/TemplateUI#22]
When you're binding to properties of the tag control i.e. the BackgroundColor it binds correctly however does not reflect any later changes in the binding context.

For example consider the following code:

```
<controls:Tag
                            Text="{Binding Text}"
                            BackgroundColor="{Binding Color}" />
```
This binds correctly when it renders first, however if the underlying "Color" property later changes at runtime it does not get reflected on the control.

**Comment by jsuarezruiz** [comment]
Thanks for the PR!
