### ISSUE TITLE
No dice on this repo ....

### ISSUE THREAD

**Issue by stephenhauck** [jsuarezruiz/TemplateUI#27]
I just watched the video on templated controls and pulled down this repo...

Even after fixing the reference issue reported it does not work ....

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0029	Cannot implicitly convert type 'Xamarin.Forms.Color' to 'Xamarin.Forms.Brush'	TemplateUI (net461), TemplateUI (netstandard2.0)	C:\Users\shauck\Downloads\TemplateUI-master\TemplateUI-master\src\TemplateUI\DataVisualization\AreaChart.cs	100	Active
Error	CS0029	Cannot implicitly convert type 'Xamarin.Forms.Color' to 'Xamarin.Forms.Brush'	TemplateUI (net461), TemplateUI (netstandard2.0)	C:\Users\shauck\Downloads\TemplateUI-master\TemplateUI-master\src\TemplateUI\DataVisualization\AreaChart.cs	101	Active
Error	CS0029	Cannot implicitly convert type 'Xamarin.Forms.Color' to 'Xamarin.Forms.Brush'	TemplateUI (net461), TemplateUI (netstandard2.0)	C:\Users\shauck\Downloads\TemplateUI-master\TemplateUI-master\src\TemplateUI\DataVisualization\AreaChart.cs	122	Active
Error	CS0029	Cannot implicitly convert type 'Xamarin.Forms.Color' to 'Xamarin.Forms.Brush'	TemplateUI (net461), TemplateUI (netstandard2.0)	C:\Users\shauck\Downloads\TemplateUI-master\TemplateUI-master\src\TemplateUI\DataVisualization\AreaChart.cs	123	Active

**Comment by jsuarezruiz** [comment]
The issue have been fixed. Try again and let me know if find anything :)
