### ISSUE TITLE
Add to XamarinCommunityToolkit?

### ISSUE THREAD

**Issue by AlexHedley** [jsuarezruiz/TemplateUI#3]
These look fantastic :)

Have you considered adding them to [XamarinCommunityToolkit](https://github.com/xamarin/XamarinCommunityToolkit)?

I know they already have an [AvatarView](https://github.com/xamarin/XamarinCommunityToolkit/pull/136) but I’m sure many people would use the rest.

**Comment by jsuarezruiz** [comment]
Actually, when starting the controls my idea was the Community Toolkit. For my part, I will do my best to move as many controls as possible. However, many controls are made up of Shapes available in Xamarin.Forms 4.7 while the Toolkit uses 4.5. We will have to wait in some cases.

**Comment by abdu292** [comment]
@jsuarezruiz Thanks for the great work. Probably good time to move this to XamarinCommunityToolkit given XF 5.0 is out?

/cc: @AlexHedley  (You probably wanna re-open if @jsuarezruiz let's you do so)
