### ISSUE TITLE
Is TemplateUI on Nuget?

### ISSUE THREAD

**Issue by mytahir** [jsuarezruiz/TemplateUI#5]
I really want use TemplateUI in my ongoing Project, but I don't know how to go about it, is it on Nuget?

**Comment by mhrastegari** [comment]
i hope these controls will be add on Xamarin Community Toolkit 👀

**Comment by jsuarezruiz** [comment]
@mytahir Currently TemplateUI is not yet available in NuGet. But... why?. There are a couple more controls and some fixes almost ready. After merge and polish details, TemplateUI will be in NuGet.

@mhrastegary77 That is the idea!. However, there are some controls based on Shapes, etc. Shapes was added in Xamarin.Forms 4.7 and the Community Toolkit is using actually 4.5. We need to wait to move some controls, but the idea is to bring as many controls as possible to the Community  Toolkit.

**Comment by mhrastegari** [comment]
@jsuarezruiz thanks :D that's amazing, can't wait to use these awesome controls in my projects!!!

**Comment by mytahir** [comment]
Thank you @jsuarezruiz for the reply, you are really doing great on Xamarin. This will help reduce time consuming and some complexities in Xamarin which are the very things People complaining about in Xamarin(including me) but to my Perspective XamarinComunityToolkit and TemplateUI could go independently without merging them, because merging them will reduce some of TemplateUI Features which are awesome and amazing. But what the Team decide is the Best!!!. Thank you
